version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    command: npm run start

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /usr/share/nginx/html
      - /app/node_modules
    command: nginx -g daemon off;

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
