version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    command: npm run start

    environment:
      - CHOKIDAR_USEPOLLING=true
